# Generated by Django 4.2.13 on 2024-05-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_remove_recipe_favourite_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
