# Generated by Django 4.2.13 on 2024-05-29 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('asian', 'asian'), ('american', 'american'), ('japan', 'japan'), ('arabian', 'arabian')], default='uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
